spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kb?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update
        format_sql: true
        show_sql: true
